# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'doctor.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DoctorWindow(object):
    def setupUi(self, DoctorWindow):
        DoctorWindow.setObjectName("DoctorWindow")
        DoctorWindow.resize(412, 61)
        self.centralwidget = QtWidgets.QWidget(DoctorWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 111, 25))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(130, 10, 131, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(270, 10, 131, 25))
        self.pushButton_3.setObjectName("pushButton_3")
        DoctorWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(DoctorWindow)
        self.statusbar.setObjectName("statusbar")
        DoctorWindow.setStatusBar(self.statusbar)

        self.retranslateUi(DoctorWindow)
        QtCore.QMetaObject.connectSlotsByName(DoctorWindow)

    def retranslateUi(self, DoctorWindow):
        _translate = QtCore.QCoreApplication.translate
        DoctorWindow.setWindowTitle(_translate("DoctorWindow", "MainWindow"))
        self.pushButton.setText(_translate("DoctorWindow", "Doctor Login"))
        self.pushButton_2.setText(_translate("DoctorWindow", "Doctor Sign-up"))
        self.pushButton_3.setText(_translate("DoctorWindow", "Export Data"))
        self.pushButton.clicked.connect(self.on_click)
        self.pushButton_2.clicked.connect(self.on_click2)
    
    def on_click(self):
        import os
        os.system("gnome-terminal -- python3 doctor_login.py")
    
    def on_click2(self):
        import os
        os.system("gnome-terminal -- python3 doctor_sign.py")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DoctorWindow = QtWidgets.QMainWindow()
    ui = Ui_DoctorWindow()
    ui.setupUi(DoctorWindow)
    DoctorWindow.show()
    sys.exit(app.exec_())
