# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'patient.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PatientWindow(object):
    def setupUi(self, PatientWindow):
        PatientWindow.setObjectName("PatientWindow")
        PatientWindow.resize(410, 79)
        self.centralwidget = QtWidgets.QWidget(PatientWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 111, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(130, 10, 131, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(270, 10, 131, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        PatientWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(PatientWindow)
        self.statusbar.setObjectName("statusbar")
        PatientWindow.setStatusBar(self.statusbar)

        self.retranslateUi(PatientWindow)
        QtCore.QMetaObject.connectSlotsByName(PatientWindow)

    def retranslateUi(self, PatientWindow):
        _translate = QtCore.QCoreApplication.translate
        PatientWindow.setWindowTitle(_translate("PatientWindow", "MainWindow"))
        self.pushButton.setText(_translate("PatientWindow", "Patient\n"
"Login"))
        self.pushButton_2.setText(_translate("PatientWindow", "Patient\n"
"Sign-up"))
        self.pushButton_3.setText(_translate("PatientWindow", "Export Data"))
        self.pushButton.clicked.connect(self.on_click)
        self.pushButton_2.clicked.connect(self.on_click2)
    
    def on_click(self):
        import os
        os.system("gnome-terminal -- python3 patient_login.py")
    
    def on_click2(self):
        import os
        os.system("gnome-terminal -- python3 patient_sign.py")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PatientWindow = QtWidgets.QMainWindow()
    ui = Ui_PatientWindow()
    ui.setupUi(PatientWindow)
    PatientWindow.show()
    sys.exit(app.exec_())
